### ISSUE TITLE
Un po' di studio sul tema dell' "Exception Handling"

### ISSUE THREAD

**Issue by fenix-hub** [Lola-bunny-owo/THE_ONE_IN_THE_DARK#13]
Le Exception sono un tema bollente, soprattutto in Java.
Un consiglio generale è quello di **gestirle**, sempre.
Gestire una exception significa sostanzialmente inserirla in un blocco try {} catch {} ( finally {} ) , catturarla e abilitare della logica tua di gestione.
In alcuni punti del codice lo fai, e va bene, ma spesso nel blocco catch() utilizzi un System.print.out.
Dal momento che non vuoi printare la exception nella console del giocare, ha senso come logica, il problema è che sia il giocatore (che tu programmatrice!) perdi la possibilità di capire perchè si è verificata l'exception e gestirla.
Potresti ad esempio pensare di salvare lo "stackTrace()" exception all'interno di un file di log. In questa maniera non perdi l'informazione.

In ogni caso, sei tu la programmatrice.
Se sai che una Exception può essere sollevata, e rappresenta un problema di configurazione del tuo programma, devi:
A) impedire che l'errore accada in primo luogo
B) non definire metodi che possano fare il throw dell'exception
C) se proprio un metodo fa un throw di una exception, catturala SEMPRE nei metodi che chiamano il metodo con l'exception

https://github.com/Lola-bunny-owo/THE_ONE_IN_THE_DARK/blob/c5fd422437322464c664df2e42e2f28104840899/src/main/java/com/angelamileti/GestioneIO.java#L29

https://www.javatpoint.com/exception-handling-in-java

**Comment by Lola-bunny-owo** [comment]
Hai ragione. Il consiglio per il file di log è ottimo, anche perché come dicevi tu non voglio mostrare all'utente lo stackTrace(). In ogni caso, grazie per avermi sottolineato la cosa! Applicherò i tuoi consigli.
